name: publish
on: [push]
jobs:
publish-ConCERTS-device-image:
runs-on: ubuntu-latest
steps:
- uses actions/checkout@v2
-name: Login to Github Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the ConCERTS Device image
run:
  docker build . --tag ghcr.io/CRLTeam/ConCERTS-Device:latest
  docker run ghcr.io/CRLTeam/ConCERTS-Device:latest
  docker push ghcr.io/CRLTeam/ConCERTS-Device:latest
